### ISSUE TITLE
丢消息

### ISSUE THREAD

**Issue by chenxijunlove** [Terry-Mao/goim#132]
客户端正常连接情况下（一直有心跳上传），过个10分钟再push消息，第一条会丢失，第二条能正常收到

**Comment by im-qq** [comment]
能否看到消息到达那里后丢失的呢，是在logic、job、comet、client？

**Comment by chenxijunlove** [comment]
logic数据没写进kafka，但logic下kafka.go handleSuccess()已执行，并打印了producer message success日志

**Comment by jie123108** [comment]
我也发现有这个问题，但是是过多长时间，我没确定。
反正是时间久了，发送的第一条消息就会丢失掉，第二条就能正常收到，看起来是个BUG。应该不是个例。

**Comment by jie123108** [comment]
第一条消息的日志：
==> logic.log <==
[09/02/16 11:24:38] [INFO] req: "/1/push/room?rid=1", post: "{"msg":"测试消息001","type":1}", res:"{"ret":1}", ip:"172.17.11.165:52561", time:"0.000199s"
[09/02/16 11:24:38] [INFO] producer message success, partition:0 offset:0 key:[0 0 0 1] valus:{"op":"broadcast_room","roomid":1,"msg":"eyJtc2ciOiLmtYvor5Xmtojmga8wMDEiLCJ0eXBlIjoxfQ=="}


第二条消息的日志：
==> logic.log <==
[09/02/16 11:26:03] [INFO] req: "/1/push/room?rid=1", post: "{"msg":"测试消息02","type":1}", res:"{"ret":1}", ip:"172.17.11.165:52581", time:"0.000233s"
[09/02/16 11:26:03] [INFO] producer message success, partition:0 offset:0 key:[0 0 0 1] valus:{"op":"broadcast_room","roomid":1,"msg":"eyJtc2ciOiLmtYvor5Xmtojmga8wMiIsInR5cGUiOjF9"}

==> job.log <==
[Sarama] 2016/09/02 11:26:03 consumer/broker/0 abandoned subscription to KafkaPushsTopic/0 because consuming was taking too long
[Sarama] 2016/09/02 11:26:03 consumer/broker/0 added subscription to KafkaPushsTopic/0
[09/02/16 11:26:03] [INFO] deal with topic:KafkaPushsTopic, partitionId:0, Offset:368, Key: msg:{"op":"broadcast_room","roomid":1,"msg":"eyJtc2ciOiLmtYvor5Xmtojmga8wMiIsInR5cGUiOjF9"}

**Comment by im-qq** [comment]
看一下comet的debug有没有给client发送消息呢

**Comment by jie123108** [comment]
没有日志，我上面的日志，是tail -f *.log 看到的。可以看到第一次的时候,job中就没有日志。

**Comment by im-qq** [comment]
看日志是从kafka没取到第一条消息，有可能sarama客户端有bug，你使用什么版本的呢？

**Comment by jie123108** [comment]
使用的是 github.com\Shopify\sarama 8月12号的版本。后面没再更新过。

**Comment by eric-hon** [comment]
这个丢消息是因为你的客户端socket关掉了吧

**Comment by jie123108** [comment]
客户端没有关，如果客户端关掉了，第二，三四条怎么收到的。

**Comment by jie123108** [comment]
仔细看了下logic的日志：
根据deal with topic:KafkaPushsTopic, partitionId:0, Offset:368, 一行的记录，应该是logic没写入到kafka中去。因为缺失的那条信息，并没有占用offset号。 
本来想直接查看kafka的队列里面的数据，找了很久也没找到办法。

**Comment by jie123108** [comment]
追查了一下，发现，连接是被kafka服务器关闭的，设置是：
`connections.max.idle.ms	
Close idle connections after the number of milliseconds specified by this config.	
long	540000
`
但是奇怪之处大于，9分钟后:
第一次发送，socket并没出错，根据job中的offset，能确认，该条消息也没成功存储到kafka。
第二次才会出错（write: broken pipe)，然后触发重连，所以第二次发送成功了。

**Comment by im-qq** [comment]
logic: kafka.go

config.Producer.RequiredAcks = sarama.NoResponse
配置为：
config.Producer.RequiredAcks = sarama.WaitForLocal

通过这个配置可以确保消息，如果发送失败时会有个retry逻辑。

**Comment by af913337456** [comment]
这个问题，知道原因了，没更新代码 ?

**Comment by im-qq** [comment]
develop 已经更新

**Comment by af913337456** [comment]
谢谢，可以告知下哪次 Commit 吗？

**Comment by im-qq** [comment]
logic: kafka.go

config.Producer.RequiredAcks = sarama.NoResponse
配置为：
config.Producer.RequiredAcks = sarama.WaitForLocal

通过这个配置可以确保消息，如果发送失败时会有个retry逻辑。

可以看看kafka.go最后提交

**Comment by af913337456** [comment]
OK

**Comment by af913337456** [comment]
额，我看了，还没修改的，不信你去看看。

func InitKafka(kafkaAddrs []string) (err error) {
	config := sarama.NewConfig()
	config.Producer.RequiredAcks = sarama.NoResponse // 还没改
	config.Producer.Partitioner = sarama.NewHashPartitioner
	config.Producer.Return.Successes = true
	config.Producer.Return.Errors = true
	producer, err = sarama.NewAsyncProducer(kafkaAddrs, config)
	go handleSuccess()
	go handleError()
	return
}

**Comment by im-qq** [comment]
在develop分支
